version: '3.8'

services:
  currency:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency
    ports:
      - '8080:8080'
    volumes:
      - ./:/currency_converter
    env_file:
      - .env

    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080"